import { spawn, all } from 'redux-saga/effects'
import {
  watchAddFormTemplateComponent,
  watchAddScreenComponent,
  watchAddScreenTemplateComponent,
  watchCreateApp,
  watchCreateAppTemplate,
  watchCreateFormTemplate,
  watchCreateScreen,
  watchCreateScreenTemplate,
  watchCreateTemplateScreen,
  watchGetForm,
  watchGetScreen,
  watchGetScreenTemplate,
  watchGetTemplateScreen,
  watchGetApp,
  watchGetApps,
  watchGetAppScreens,
  watchGetAppTemplates,
  watchGetAppTemplate,
  watchGetAppTemplateScreens,
  watchGetForms,
  watchGetFormTemplate,
  watchGetFormTemplates,
  watchGetScreens,
  watchGetScreenTemplates,
  watchPreview,
  watchPublish,
  watchUpdateAppTemplateScreen,
  watchUpdateFormTemplate,
  watchUpdateScreen,
  watchUpdateScreenTemplate,
} from './app_sagas'

const rootSaga = function* () {
  yield all([
    spawn(watchAddFormTemplateComponent),
    spawn(watchAddScreenComponent),
    spawn(watchAddScreenTemplateComponent),
    spawn(watchCreateApp),
    spawn(watchCreateAppTemplate),
    spawn(watchCreateFormTemplate),
    spawn(watchCreateScreen),
    spawn(watchCreateScreenTemplate),
    spawn(watchGetApp),
    spawn(watchGetAppTemplate),
    spawn(watchGetForm),
    spawn(watchGetForms),
    spawn(watchGetFormTemplate),
    spawn(watchGetFormTemplates),
    spawn(watchGetScreen),
    spawn(watchGetScreenTemplate),
    spawn(watchGetTemplateScreen),
    spawn(watchGetAppTemplateScreens),
    spawn(watchGetApps),
    spawn(watchGetAppScreens),
    spawn(watchGetAppTemplates),
    spawn(watchGetScreens),
    spawn(watchGetScreenTemplates),
    spawn(watchCreateTemplateScreen),
    spawn(watchPreview),
    spawn(watchPublish),
    spawn(watchUpdateAppTemplateScreen),
    spawn(watchUpdateFormTemplate),
    spawn(watchUpdateScreen),
    spawn(watchUpdateScreenTemplate),
  ])
}

export default rootSaga
